ALTER TABLE empresas ADD COLUMN ie                 TEXT;
ALTER TABLE empresas ADD COLUMN im                 TEXT;
ALTER TABLE empresas ADD COLUMN cnae               TEXT;
ALTER TABLE empresas ADD COLUMN regime_tributario  INTEGER DEFAULT 1;
ALTER TABLE empresas ADD COLUMN crt                INTEGER DEFAULT 1;
ALTER TABLE empresas ADD COLUMN email              TEXT;
ALTER TABLE empresas ADD COLUMN telefone           TEXT;
ALTER TABLE empresas ADD COLUMN cep                TEXT;
ALTER TABLE empresas ADD COLUMN endereco           TEXT;
ALTER TABLE empresas ADD COLUMN numero             TEXT;
ALTER TABLE empresas ADD COLUMN complemento        TEXT;
ALTER TABLE empresas ADD COLUMN bairro             TEXT;
ALTER TABLE empresas ADD COLUMN cidade             TEXT;
ALTER TABLE empresas ADD COLUMN cod_municipio_ibge TEXT;
ALTER TABLE empresas ADD COLUMN estado             TEXT;
ALTER TABLE empresas ADD COLUMN cod_pais           TEXT DEFAULT '1058';
ALTER TABLE empresas ADD COLUMN nome_pais          TEXT DEFAULT 'Brasil';
ALTER TABLE empresas ADD COLUMN serie_nfe          INTEGER DEFAULT 1;
ALTER TABLE empresas ADD COLUMN prox_nfe           INTEGER DEFAULT 1;
ALTER TABLE empresas ADD COLUMN serie_nfce         INTEGER DEFAULT 1;
ALTER TABLE empresas ADD COLUMN prox_nfce          INTEGER DEFAULT 1;
ALTER TABLE empresas ADD COLUMN serie_nfse         INTEGER DEFAULT 1;
ALTER TABLE empresas ADD COLUMN prox_nfse          INTEGER DEFAULT 1;
ALTER TABLE empresas ADD COLUMN serie_cte          INTEGER DEFAULT 1;
ALTER TABLE empresas ADD COLUMN prox_cte           INTEGER DEFAULT 1;
ALTER TABLE empresas ADD COLUMN ambiente_fiscal    INTEGER DEFAULT 2;
ALTER TABLE empresas ADD COLUMN cert_path          TEXT;
ALTER TABLE empresas ADD COLUMN cert_senha         TEXT;